slack_token: SLACK_BOT_TOKEN
bot_name: talkingbop
puppetron: http://127.0.0.1:8080/screenshot/
graph_urls:
  hacktoberfest: https://hacktoberfest.digitalocean.com
  google: https://www.google.com
  walmart: https://www.walmart.com
  sams: https://www.samsclub.com
  asda: https://www.asda.com
  walmartca: https://www.walmart.ca
  amazon: https://www.amazon.com
  globo: https://www.globo.com
  uol: https://www.uol.com
